In [2]:

import pandas as pd
from pathlib import Path

In [3]:
Path.cwd()

WindowsPath('C:/work/busan_port_project/ tablet_notebook')

In [7]:
df = pd.read_csv(
    "../data/raw(원본)/2020_2021.csv",
    encoding="utf-8-sig",
    header=None
)

In [5]:
df.shape

(671, 20)

In [6]:
df.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,NaN,전년대비증감율(%),NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,12월,NaN,NaN,누계(01월~12월),NaN,NaN,12월,NaN,NaN,누계(01월~12월),NaN,NaN,12월,NaN,NaN,누계(01월~12월),NaN,NaN
2,입출항구분,국가명,계,적,공,계,적,공,계,적,공,계,적,공,증감_계,증감_적,증감_공,증감_계,증감_적,증감_공
3,합계,NaN,1878193.75,1606646.25,271547.5,2.1823961E7,1.8228629E7,3595332.0,1864930.0,1602183.5,262746.5,2.270612375E7,1.954508125E7,3161042.5,-0.7061971109210696,-0.27776805255046444,-3.241053590992371,4.0421752494884,7.221893923015266,-12.079259996017056
4,입항소계,NaN,426819.75,254564.5,172255.25,4852616.75,3058235.5,1794381.25,441325.75,279567.5,161758.25,5207989.5,3227561.75,1980427.75,3.398624360751823,9.821872256343678,-6.093863612284678,7.323321999414034,5.536730248537114,10.368281545518832
5,입항,가나,29.0,29.0,0.0,774.0,774.0,0.0,9.0,9.0,0.0,382.0,376.0,6.0,-68.96551724137932,-68.96551724137932,NaN,-50.64599483204134,-51.42118863049095,0
6,NaN,가봉,NaN,NaN,NaN,9.0,9.0,0.0,10.0,10.0,0.0,64.0,64.0,0.0,0,0,NaN,611.1111111111111,611.1111111111111,NaN
7,NaN,가이아나,NaN,NaN,NaN,79.0,79.0,0.0,1.0,1.0,0.0,45.0,43.0,2.0,0,0,NaN,-43.0379746835443,-45.56962025316456,0
8,NaN,감비아,6.0,6.0,0.0,98.0,98.0,0.0,3.0,3.0,0.0,58.0,58.0,0.0,-50.0,-50.0,NaN,-40.816326530612244,-40.816326530612244,NaN
9,NaN,과들루프,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,0.0,4.0,4.0,0.0,0,0,NaN,0,0,NaN
10,NaN,과테말라,253.0,223.0,30.0,6007.0,3519.0,2488.0,210.0,196.0,14.0,4658.0,3383.0,1275.0,-16.996047430830043,-12.107623318385652,-53.333333333333336,-22.4571333444315,-3.864734299516903,-48.7540192926045
11,NaN,괌,1015.0,73.0,942.0,10166.0,708.0,9458.0,125.0,92.0,33.0,6969.0,1068.5,5900.5,-87.68472906403942,26.027397260273965,-96.4968152866242,-31.447963800904976,50.9180790960452,-37.61366039331783
12,NaN,그리스,1178.0,370.0,808.0,13427.0,4385.0,9042.0,252.0,162.0,90.0,11364.25,4371.0,6993.25,-78.60780984719864,-56.21621621621622,-88.86138613861387,-15.362702018321295,-0.31927023945268473,-22.658150851581503
13,NaN,기니,36.0,36.0,0.0,886.0,886.0,0.0,79.0,79.0,0.0,937.0,937.0,0.0,119.44444444444446,119.44444444444446,NaN,5.756207674943559,5.756207674943559,NaN
14,NaN,기니비사우,4.0,4.0,0.0,32.0,32.0,0.0,NaN,NaN,NaN,42.0,42.0,0.0,-100,-100,NaN,31.25,31.25,NaN

In [8]:
# 앞쪽 헤더와 누계 컬럼 위치 확인
df.iloc[:6, :14]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,12월,NaN,NaN,누계(01월~12월),NaN,NaN,12월,NaN,NaN,누계(01월~12월),NaN,NaN
2,입출항구분,국가명,계,적,공,계,적,공,계,적,공,계,적,공
3,합계,NaN,1878193.75,1606646.25,271547.5,2.1823961E7,1.8228629E7,3595332.0,1864930.0,1602183.5,262746.5,2.270612375E7,1.954508125E7,3161042.5
4,입항소계,NaN,426819.75,254564.5,172255.25,4852616.75,3058235.5,1794381.25,441325.75,279567.5,161758.25,5207989.5,3227561.75,1980427.75
5,입항,가나,29.0,29.0,0.0,774.0,774.0,0.0,9.0,9.0,0.0,382.0,376.0,6.0

In [9]:
# 필요한 열만 선택
df1 = df.iloc[:, [0, 1, 5, 11]]

df1.head(10)

      0     1            5              11
0    NaN   NaN          NaN            NaN
1    NaN   NaN  누계(01월~12월)    누계(01월~12월)
2  입출항구분   국가명            계              계
3     합계   NaN  2.1823961E7  2.270612375E7
4   입항소계   NaN   4852616.75      5207989.5
5     입항    가나        774.0          382.0
6    NaN    가봉          9.0           64.0
7    NaN  가이아나         79.0           45.0
8    NaN   감비아         98.0           58.0
9    NaN  과들루프          NaN            4.0

In [10]:
# 위쪽 헤더 부분 제거
df1 = df1.iloc[3:].copy()

df1.head()

     0     1            5              11
3    합계   NaN  2.1823961E7  2.270612375E7
4  입항소계   NaN   4852616.75      5207989.5
5    입항    가나        774.0          382.0
6   NaN    가봉          9.0           64.0
7   NaN  가이아나         79.0           45.0

In [13]:
df1.columns

Index([0, 1, 5, 11], dtype='int64')

In [14]:
# 컬럼명 변경
df1.columns = [
    '입출항구분',
    '국가명',
    '2020',
    '2021'
]

In [15]:
df1.columns

Index(['입출항구분', '국가명', '2020', '2021'], dtype='str')

In [18]:
# 원본 df에서 필요한 열을 다시 선택
df1 = df.iloc[:, [0, 1, 5, 11]].copy()

# 컬럼명 변경
df1.columns = [
    '입출항구분',
    '국가명',
    '2020',
    '2021'
]

# 원본 위쪽 3개 헤더 행 제거
df1 = df1.iloc[3:].copy()

# 입출항구분의 빈칸을 위의 값으로 채움
df1['입출항구분'] = df1['입출항구분'].ffill()

# 국가명이 없는 합계/소계 행 제거
df1 = df1.dropna(subset=['국가명'])

# 확인
df1['입출항구분'].value_counts()# 원본 df에서 필요한 열을 다시 선택
df1 = df.iloc[:, [0, 1, 5, 11]].copy()

# 컬럼명 변경
df1.columns = [
    '입출항구분',
    '국가명',
    '2020',
    '2021'
]

# 원본 위쪽 3개 헤더 행 제거
df1 = df1.iloc[3:].copy()

# 입출항구분의 빈칸을 위의 값으로 채움
df1['입출항구분'] = df1['입출항구분'].ffill()

# 국가명이 없는 합계/소계 행 제거
df1 = df1.dropna(subset=['국가명'])

# 확인
df1['입출항구분'].value_counts()

입출항구분
출항환적    172
입항      164
입항환적    164
출항      163
Name: count, dtype: int64

In [19]:
# 현재 데이터 크기 확인
df1.shape

(663, 4)

In [20]:
# 결측치 확인
df1.isna().sum()

입출항구분     0
국가명       0
2020     21
2021     22
dtype: int64

In [21]:
# 물동량 데이터를 숫자형으로 변환
df1['2020'] = pd.to_numeric(df1['2020'], errors='coerce')
df1['2021'] = pd.to_numeric(df1['2021'], errors='coerce')df1.isna().sum()

In [22]:
df1.isna().sum()

입출항구분     0
국가명       0
2020     21
2021     22
dtype: int64

In [24]:
# 2020 또는 2021 물동량이 비어 있는 행 확인
df1[
    df1['2020'].isna() |
    df1['2021'].isna()
]

    입출항구분           국가명  2020  2021
9      입항          과들루프   NaN   4.0
27     입항       도미니카 연방   2.0   NaN
42     입항            말리   2.0   NaN
55     입항         바베이도스  20.0   NaN
62     입항           벨리즈   1.0   NaN
72     입항  세인트 빈센트 그레나딘  10.0   NaN
87     입항           아루바   NaN  10.0
103    입항         오스트리아   NaN   2.0
122    입항          지브롤터  29.0   NaN
126    입항        카보 베르데   NaN   2.0
131    입항           코모로   3.0   NaN
139    입항           퀴라소   NaN  10.0
155    입항         페로 제도   2.0   NaN
181    출항           나우루   NaN   1.0
193    출항       도미니카 연방   5.0   NaN
208    출항           마카오   1.0   NaN
235    출항          브루나이   NaN   5.0
288    출항          지브롤터   1.0   NaN
291    출항        카보 베르데   NaN   5.0
343  입항환적         기니비사우   4.0   NaN
344  입항환적          기타국가  15.0   NaN
357  입항환적       도미니카 연방   NaN   1.0
360  입항환적         라이베리아   NaN   1.0
371  입항환적           마카오   2.0   NaN
389  입항환적            베냉   NaN  96.0
415  입항환적           아루바   NaN  88.0
424  입항환적       앤티가 바부다   NaN   6.0
432  입항환적         오스트리아   NaN   2.0
438  입항환적           이라크  78.0   NaN
439  입항환적            이란   NaN   2.0
451  입항환적          지브롤터   NaN   4.0
452  입항환적            차드   1.0   NaN
453  입항환적            체코   1.0   NaN
456  입항환적        카보 베르데  18.0   NaN
461  입항환적           코모로   2.0   NaN
536  출항환적           마요트   NaN   7.0
556  출항환적           버뮤다   NaN   2.0
562  출항환적          볼리비아   6.0   NaN
569  출항환적      상투메 프린시페   NaN   2.0
607  출항환적       왈리스 푸투나   NaN   2.0
627  출항환적        카보 베르데   1.0   NaN
633  출항환적           코모로   NaN   4.0
650  출항환적           투발루   2.0   NaN

In [25]:
# 물동량이 없는 빈칸을 0으로 처리
df1[['2020', '2021']] = df1[['2020', '2021']].fillna(0)

# 결측치가 모두 처리됐는지 확인
df1.isna().sum()

입출항구분    0
국가명      0
2020     0
2021     0
dtype: int64

In [26]:
df1.dtypes

입출항구분        str
국가명          str
2020     float64
2021     float64
dtype: object

In [27]:
df1.head(10)

   입출항구분    국가명     2020      2021
5     입항     가나    774.0    382.00
6     입항     가봉      9.0     64.00
7     입항   가이아나     79.0     45.00
8     입항    감비아     98.0     58.00
9     입항   과들루프      0.0      4.00
10    입항   과테말라   6007.0   4658.00
11    입항      괌  10166.0   6969.00
12    입항    그리스  13427.0  11364.25
13    입항     기니    886.0    937.00
14    입항  기니비사우     32.0     42.00

In [28]:
# 2020, 2021 연도별 열을 세로 형태로 변환
df1_long = df1.melt(
    id_vars=['입출항구분', '국가명'],
    value_vars=['2020', '2021'],
    var_name='연도',
    value_name='물동량'
)

df1_long.head()

  입출항구분   국가명    연도    물동량
0    입항    가나  2020  774.0
1    입항    가봉  2020    9.0
2    입항  가이아나  2020   79.0
3    입항   감비아  2020   98.0
4    입항  과들루프  2020    0.0

In [29]:
df1_long['연도'] = df1_long['연도'].astype(int)

In [30]:
df1_long.dtypes

입출항구분        str
국가명          str
연도         int64
물동량      float64
dtype: object

In [31]:
df1_long.shape

(1326, 4)

In [32]:
df1_long['입출항구분'].value_counts()

입출항구분
출항환적    344
입항      328
입항환적    328
출항      326
Name: count, dtype: int64

In [33]:
# 수입 데이터
import_df = df1_long[
    df1_long['입출항구분'] == '입항'
].copy()

import_df.head()

  입출항구분   국가명    연도    물동량
0    입항    가나  2020  774.0
1    입항    가봉  2020    9.0
2    입항  가이아나  2020   79.0
3    입항   감비아  2020   98.0
4    입항  과들루프  2020    0.0

In [34]:
# 수출 데이터
export_df = df1_long[
    df1_long['입출항구분'] == '출항'
].copy()

export_df.head()

    입출항구분   국가명    연도     물동량
164    출항    가나  2020  3203.0
165    출항    가봉  2020    16.0
166    출항  가이아나  2020    73.0
167    출항   감비아  2020     6.0
168    출항  과들루프  2020    21.0

In [35]:
# 환적 데이터만 선택
trans_df = df1_long[
    df1_long['입출항구분'].isin(['입항환적', '출항환적'])
].copy()

trans_df.head()

    입출항구분   국가명    연도     물동량
327  입항환적    가나  2020   545.0
328  입항환적    가봉  2020   926.0
329  입항환적  가이아나  2020  2249.0
330  입항환적   감비아  2020    14.0
331  입항환적  과들루프  2020    14.0

In [36]:
# 입항환적 + 출항환적 합계
trans_df = (
    trans_df
    .groupby(['연도', '국가명'])['물동량']
    .sum()
    .reset_index()
)

trans_df.head()

     연도   국가명     물동량
0  2020    가나  1798.5
1  2020    가봉   984.0
2  2020  가이아나  4860.0
3  2020   감비아   134.0
4  2020  과들루프   182.0

In [37]:
# 국가별 전체 물동량
total_df = (
    df1_long
    .groupby(['연도', '국가명'])['물동량']
    .sum()
    .reset_index()
)

total_df.head()

     연도   국가명     물동량
0  2020    가나  5775.5
1  2020    가봉  1009.0
2  2020  가이아나  5012.0
3  2020   감비아   238.0
4  2020  과들루프   203.0

In [38]:
total_df[
    total_df['연도'] == 2020
].sort_values(
    '물동량',
    ascending=False
).head(10)

       연도   국가명         물동량
131  2020    중국  6116158.50
51   2020    미국  3231559.00
127  2020    일본  2986053.00
141  2020   캐나다   676687.00
30   2020   러시아   624812.25
63   2020   베트남   594097.00
43   2020   멕시코   541746.25
22   2020  대한민국   454259.25
158  2020    태국   366566.00
21   2020    대만   360152.00